export const PROBATION_SUCCESS_THRESHOLD = 5;
export const QUALIFYING_FAILURE_THRESHOLD = 2;
export const QUALIFYING_FAILURE_WINDOW_MS = 15 * 60_000;
export const OPPORTUNITY_WINDOW_MS = 10 * 60_000;
export const OPPORTUNITY_TIMEOUT_MS = 7 * 24 * 60 * 60_000;
